-- Add slots from CSV file
-- This script adds all slots from the uploaded CSV

INSERT INTO slots (game_name, provider) VALUES
('7 Sins', 'Play''n GO'),
('Rusty & Curly', 'Hacksaw Gaming'),
('Big Win Cat', 'Play''n GO'),
('Chaos Crew', 'Hacksaw Gaming'),
('Book of Dead', 'Play''n GO'),
('Wanted Dead or a Wild', 'Hacksaw Gaming'),
('Fire in the Hole', 'No Limit City'),
('Mental', 'No Limit City'),
('Tombstone', 'No Limit City'),
('San Quentin', 'No Limit City'),
('East Coast vs West Coast', 'No Limit City'),
('Punk Rocker', 'No Limit City'),
('Deadwood', 'No Limit City'),
('El Paso Gunfight', 'No Limit City'),
('Folsom Prison', 'No Limit City'),
('Karen Maneater', 'No Limit City'),
('Das xBoot', 'No Limit City'),
('Barbarian Fury', 'No Limit City'),
('Misery Mining', 'No Limit City'),
('Remember Gulag', 'No Limit City'),
('Serial', 'No Limit City'),
('Warrior Graveyard', 'No Limit City'),
('Pixies vs Pirates', 'No Limit City'),
('The Rave', 'No Limit City'),
('Outsourced', 'No Limit City'),
('Harlequin Carnival', 'No Limit City'),
('Poison Eve', 'No Limit City'),
('Bonus Bunnies', 'No Limit City'),
('Fire in the Hole 2', 'No Limit City'),
('Fire in the Hole xBomb', 'No Limit City'),
('Punk Toilet', 'No Limit City'),
('Milky Ways', 'No Limit City'),
('Starstruck', 'No Limit City'),
('Tractor Beam', 'No Limit City'),
('Infectious 5 xWays', 'No Limit City'),
('Wixx', 'No Limit City'),
('Tomb of Akhenaten', 'No Limit City'),
('Manhattan Goes Wild', 'No Limit City'),
('Narcos', 'No Limit City'),
('Road Rage', 'No Limit City'),
('Bushido Ways xNudge', 'No Limit City'),
('Tesla Jolt', 'No Limit City'),
('Dungeon Quest', 'No Limit City'),
('Oktoberfest', 'No Limit City'),
('Punk Rocker xWays', 'No Limit City'),
('Book of Shadows', 'No Limit City'),
('Tomb of Nefertiti', 'No Limit City'),
('Kitchen Drama BBQ Frenzy', 'No Limit City'),
('Kitchen Drama Sushi Mania', 'No Limit City'),
('Bonus Bunnies Cluster Craze', 'No Limit City'),
('Sweet Bonanza', 'Pragmatic Play'),
('Gates of Olympus', 'Pragmatic Play'),
('Sugar Rush', 'Pragmatic Play'),
('Starlight Princess', 'Pragmatic Play'),
('The Dog House', 'Pragmatic Play'),
('Big Bass Bonanza', 'Pragmatic Play'),
('Wolf Gold', 'Pragmatic Play'),
('Great Rhino Megaways', 'Pragmatic Play'),
('Fruit Party', 'Pragmatic Play'),
('Madame Destiny Megaways', 'Pragmatic Play'),
('Wild West Gold', 'Pragmatic Play'),
('John Hunter and the Tomb of the Scarab Queen', 'Pragmatic Play'),
('Chilli Heat', 'Pragmatic Play'),
('Mustang Gold', 'Pragmatic Play'),
('Buffalo King', 'Pragmatic Play'),
('Pirate Gold Deluxe', 'Pragmatic Play'),
('Aztec Gems', 'Pragmatic Play'),
('Sweet Bonanza Xmas', 'Pragmatic Play'),
('Gates of Olympus 1000', 'Pragmatic Play'),
('Starlight Princess 1000', 'Pragmatic Play'),
('Sugar Rush 1000', 'Pragmatic Play'),
('Big Bass Amazon Xtreme', 'Pragmatic Play'),
('Bigger Bass Bonanza', 'Pragmatic Play'),
('Big Bass Splash', 'Pragmatic Play'),
('Floating Dragon', 'Pragmatic Play'),
('Fruit Party 2', 'Pragmatic Play'),
('The Dog House Megaways', 'Pragmatic Play'),
('Wild Wild Riches', 'Pragmatic Play'),
('Gems Bonanza', 'Pragmatic Play'),
('Chicken Drop', 'Pragmatic Play'),
('Candy Stars', 'Pragmatic Play'),
('Aztec Bonanza', 'Pragmatic Play'),
('Pyramid Bonanza', 'Pragmatic Play'),
('Sword of Ares', 'Pragmatic Play'),
('Forge of Olympus', 'Pragmatic Play'),
('Cleocatra', 'Pragmatic Play'),
('Reactoonz', 'Play''n GO'),
('Moon Princess', 'Play''n GO'),
('Rise of Olympus', 'Play''n GO'),
('Tome of Madness', 'Play''n GO'),
('Legacy of Dead', 'Play''n GO'),
('Fire Joker', 'Play''n GO'),
('Gemix', 'Play''n GO'),
('Viking Runecraft', 'Play''n GO'),
('Golden Ticket', 'Play''n GO'),
('Pimped', 'Play''n GO'),
('Reactoonz 2', 'Play''n GO'),
('Moon Princess 100', 'Play''n GO'),
('Rise of Olympus 100', 'Play''n GO'),
('Gigantoonz', 'Play''n GO'),
('Troll Hunters 2', 'Play''n GO'),
('Raging Rex', 'Play''n GO'),
('Wild Falls', 'Play''n GO'),
('Coywolf Cash', 'Play''n GO'),
('Disco Diamonds', 'Play''n GO'),
('Honey Rush', 'Play''n GO'),
('Le Bandit', 'Hacksaw Gaming'),
('Chaos Crew 2', 'Hacksaw Gaming'),
('Stack ''Em', 'Hacksaw Gaming'),
('Cubes', 'Hacksaw Gaming'),
('Dork Unit', 'Hacksaw Gaming'),
('Bowery Boys', 'Hacksaw Gaming'),
('Gladiator Legends', 'Hacksaw Gaming'),
('Warrior Ways', 'Hacksaw Gaming'),
('Aztec Twist', 'Hacksaw Gaming'),
('Rocket Reels', 'Hacksaw Gaming'),
('Hop ''N'' Pop', 'Hacksaw Gaming'),
('Itero', 'Hacksaw Gaming'),
('Pocketz', 'Hacksaw Gaming'),
('Xpander', 'Hacksaw Gaming'),
('Mega Flip', 'Hacksaw Gaming'),
('Sticky Bombs', 'Hacksaw Gaming'),
('Wanted Dead or a Wild Megaways', 'Hacksaw Gaming'),
('Chaos Crew Scratch', 'Hacksaw Gaming'),
('Stack ''Em Scratch', 'Hacksaw Gaming'),
('Cubes 2', 'Hacksaw Gaming'),
('Money Train', 'Relax Gaming'),
('Money Train 2', 'Relax Gaming'),
('Money Train 3', 'Relax Gaming'),
('Money Train 4', 'Relax Gaming'),
('Temple Tumble', 'Relax Gaming'),
('Temple Tumble 2', 'Relax Gaming'),
('TNT Tumble', 'Relax Gaming'),
('Beast Mode', 'Relax Gaming'),
('Hellcatraz', 'Relax Gaming'),
('Iron Bank', 'Relax Gaming'),
('Volatile Vikings', 'Relax Gaming'),
('Marching Legions', 'Relax Gaming'),
('Deep Descent', 'Relax Gaming'),
('Cluster Tumble', 'Relax Gaming'),
('Mega Flip', 'Relax Gaming'),
('Banana Town', 'Relax Gaming'),
('Immortal Fruits', 'Relax Gaming'),
('Caveman Bob', 'Relax Gaming'),
('Neon Villains', 'Relax Gaming'),
('Demon', 'Relax Gaming'),
('Popstar', 'AvatarUX'),
('CherryPop', 'AvatarUX'),
('LillyPop', 'AvatarUX'),
('BountyPop', 'AvatarUX'),
('TikiPop', 'AvatarUX'),
('HippoPop', 'AvatarUX'),
('PapayaPop', 'AvatarUX'),
('RagingPop', 'AvatarUX'),
('WildPops', 'AvatarUX'),
('CritterPop', 'AvatarUX'),
('DinoPop', 'AvatarUX'),
('MonkeyPop', 'AvatarUX'),
('PiggyPop', 'AvatarUX'),
('Piggy Bank Bills', 'AvatarUX'),
('Piggy Bank Farm', 'AvatarUX'),
('Piggy Luck', 'AvatarUX'),
('Zombie Queen', 'Red Tiger'),
('Dragon''s Luck', 'Red Tiger'),
('Gonzo''s Quest Megaways', 'Red Tiger'),
('Piggy Riches Megaways', 'Red Tiger'),
('Mystery Reels', 'Red Tiger'),
('Reel King Mega', 'Red Tiger'),
('10001 Nights', 'Red Tiger'),
('Atlantis', 'Red Tiger'),
('Cinderella''s Ball', 'Red Tiger'),
('Dragon''s Fire', 'Red Tiger'),
('Esqueleto Explosivo', 'Thunderkick'),
('Pink Elephants', 'Thunderkick'),
('Riders of the Storm', 'Thunderkick'),
('Beat the Beast', 'Thunderkick'),
('Midas Golden Touch', 'Thunderkick'),
('Crystal Quest', 'Thunderkick'),
('Divine Lotus', 'Thunderkick'),
('Sword of Khans', 'Thunderkick'),
('Jammin'' Jars', 'Push Gaming'),
('Jammin'' Jars 2', 'Push Gaming'),
('Razor Shark', 'Push Gaming'),
('Fat Banker', 'Push Gaming'),
('Retro Tapes', 'Push Gaming'),
('Wild Swarm', 'Push Gaming'),
('Mystery Mission', 'Push Gaming'),
('Tiki Tumble', 'Push Gaming'),
('Mount Mazuma', 'Push Gaming'),
('Big Bamboo', 'Push Gaming'),
('Nightfall', 'Push Gaming'),
('Mad Cars', 'Push Gaming'),
('Deadly 5', 'Gamomat'),
('Books & Bulls', 'Gamomat'),
('Crystal Mirror', 'Gamomat'),
('Ramses Book', 'Gamomat'),
('El Torero', 'Gamomat'),
('Fancy Fruits', 'Gamomat'),
('Sticky Diamonds', 'Gamomat'),
('Wild Rubies', 'Gamomat'),
('Aztec Warrior Princess', 'Backseat Gaming'),
('Hypernova', 'Backseat Gaming'),
('Megaways Jack', 'Backseat Gaming'),
('Stacked', 'Backseat Gaming'),
('Tiki Wins', 'Backseat Gaming'),
('Hypernova Radiant Reels', 'Backseat Gaming'),
('Hypernova Infinity Reels', 'Backseat Gaming'),
('Hypernova Megaways', 'Backseat Gaming'),
('Hypernova 10K Ways', 'Backseat Gaming'),
('Hypernova Fortune Link', 'Backseat Gaming'),
('Hypernova Burst', 'Backseat Gaming'),
('Hypernova Avalanche', 'Backseat Gaming'),
('Hypernova Cashblast', 'Backseat Gaming'),
('Hypernova Megacluster', 'Backseat Gaming'),
('Hypernova Megaquads', 'Backseat Gaming'),
('Hypernova Megaways 2', 'Backseat Gaming'),
('Hypernova Megaways 3', 'Backseat Gaming'),
('Hypernova Megaways 4', 'Backseat Gaming'),
('Hypernova Megaways 5', 'Backseat Gaming'),
('Hypernova Megaways 6', 'Backseat Gaming'),
('Hypernova Megaways 7', 'Backseat Gaming'),
('Hypernova Megaways 8', 'Backseat Gaming'),
('Hypernova Megaways 9', 'Backseat Gaming'),
('Hypernova Megaways 10', 'Backseat Gaming'),
('Hypernova Megaways 11', 'Backseat Gaming'),
('Hypernova Megaways 12', 'Backseat Gaming'),
('Hypernova Megaways 13', 'Backseat Gaming'),
('Hypernova Megaways 14', 'Backseat Gaming'),
('Hypernova Megaways 15', 'Backseat Gaming'),
('Hypernova Megaways 16', 'Backseat Gaming'),
('Hypernova Megaways 17', 'Backseat Gaming'),
('Hypernova Megaways 18', 'Backseat Gaming'),
('Hypernova Megaways 19', 'Backseat Gaming'),
('Hypernova Megaways 20', 'Backseat Gaming')
ON CONFLICT (game_name, provider) DO NOTHING;
