-- Insert all slots with their providers
INSERT INTO slots (game_name, provider) VALUES
('7 Sins', 'Play''n GO'),
('Ankh of Anubis', 'Play''n GO'),
('Aztec Idols', 'Play''n GO'),
('Banana Rock', 'Play''n GO'),
('Battle Royal', 'Play''n GO'),
('Big Win 777', 'Play''n GO'),
('Big Win Cat', 'Play''n GO'),
('Black Mamba', 'Play''n GO'),
('Blinged', 'Play''n GO'),
('Cash Pump', 'Play''n GO'),
('Cash Vandal', 'Play''n GO'),
('Doom of Dead', 'Play''n GO'),
('Cats & Cash', 'Play''n GO'),
('Charlie Chance in Hell to Pay', 'Play''n GO'),
('Chinese New Year', 'Play''n GO'),
('Chronos Joker', 'Play''n GO'),
('Cloud Quest', 'Play''n GO'),
('Contact', 'Play''n GO'),
('Cops ''N Robbers', 'Play''n GO'),
('Coywolf Cash', 'Play''n GO'),
('Crazy Cows', 'Play''n GO'),
('Crystal Sun', 'Play''n GO'),
('Dawn of Egypt', 'Play''n GO'),
('Demon', 'Play''n GO'),
('Diamond Vortex', 'Play''n GO'),
('Disco Diamonds', 'Play''n GO'),
('Divine Showdown', 'Play''n GO'),
('Doom of Egypt', 'Play''n GO'),
('Dragon Maiden', 'Play''n GO'),
('Dragon Ship', 'Play''n GO'),
('Energoonz', 'Play''n GO'),
('Fire Joker', 'Play''n GO'),
('Firefly Frenzy', 'Play''n GO'),
('Fortune Teller', 'Play''n GO'),
('Fotune of Ali Baba', 'Play''n GO'),
('Frozen Gems', 'Play''n GO'),
('Fruit Bonanza', 'Play''n GO'),
('Fu Er Dai', 'Play''n GO'),
('Gemix', 'Play''n GO'),
('Game of Gladiators', 'Play''n GO'),
('Gift Shop', 'Play''n GO'),
('Gold King', 'Play''n GO'),
('Gold Volcano', 'Play''n GO'),
('Golden Caravan', 'Play''n GO'),
('Golden Colts', 'Play''n GO'),
('Golden Osiris', 'Play''n GO'),
('Golden Ticket', 'Play''n GO'),
('Golden Ticket 2', 'Play''n GO'),
('Grim Muerto', 'Play''n GO'),
('Gunslinger Reloaded', 'Play''n GO'),
('Holiday Season', 'Play''n GO'),
('Holiday Spirits', 'Play''n GO'),
('Honey Rush', 'Play''n GO'),
('House of Doom', 'Play''n GO'),
('Hugo', 'Play''n GO'),
('Hugo 2', 'Play''n GO'),
('Hugo Goal', 'Play''n GO'),
('Hugo''s Adventure', 'Play''n GO'),
('Ice Joker', 'Play''n GO'),
('Imperial Opera', 'Play''n GO'),
('Inferno Joker', 'Play''n GO'),
('Inferno Star', 'Play''n GO'),
('Irish Gold', 'Play''n GO'),
('Iron Girl', 'Play''n GO'),
('Jewel Box', 'Play''n GO'),
('Jolly Roger', 'Play''n GO'),
('Jolly Roger 2', 'Play''n GO'),
('Lady of Fortune', 'Play''n GO'),
('Legacy of Dead', 'Play''n GO'),
('Legacy of Egypt', 'Play''n GO'),
('Leprechaun Goes Wild', 'Play''n GO'),
('Leprechaun Goes Egypt', 'Play''n GO'),
('Leprechaun Goes to Hell', 'Play''n GO'),
('Lucky Diamonds', 'Play''n GO'),
('Madame Ink', 'Play''n GO'),
('Mahjong 88', 'Play''n GO'),
('Matsuri', 'Play''n GO'),
('Mermaid''s Diamond', 'Play''n GO'),
('Merry Xmas', 'Play''n GO'),
('Mission Cash', 'Play''n GO'),
('Moon Princess', 'Play''n GO'),
('Multifruit 81', 'Play''n GO'),
('Mystery Joker', 'Play''n GO'),
('Myth', 'Play''n GO'),
('New Year Riches', 'Play''n GO'),
('Ninja Fruits', 'Play''n GO'),
('Pearls of India', 'Play''n GO'),
('Phoenix Reborn', 'Play''n GO'),
('Pimped', 'Play''n GO'),
('Planet Fortune', 'Play''n GO'),
('Raging Rex', 'Play''n GO'),
('Rainforest Magic', 'Play''n GO'),
('Rainforest Magic Bingo', 'Play''n GO'),
('Reactoonz', 'Play''n GO'),
('Reactoonz 2', 'Play''n GO'),
('Shield of Athena', 'Play''n GO'),
('Tome of Madness', 'Play''n GO'),
('Riches of Ra', 'Play''n GO'),
('Riches of Robin', 'Play''n GO'),
('Riddle Reels', 'Play''n GO'),
('Ring of Odin', 'Play''n GO'),
('Rise of Athena', 'Play''n GO'),
('Rise of Dead', 'Play''n GO'),
('Rise of Merlin', 'Play''n GO'),
('Rise of Olympus', 'Play''n GO'),
('Royal Masquerade', 'Play''n GO'),
('Sabaton', 'Play''n GO'),
('Sails of Gold', 'Play''n GO'),
('Samba Carnival', 'Play''n GO'),
('Saxon', 'Play''n GO'),
('Star Joker', 'Play''n GO'),
('Sticky Joker', 'Play''n GO'),
('Street Magic', 'Play''n GO'),
('Sweet Alchemy', 'Play''n GO'),
('Testament', 'Play''n GO'),
('That''s Rich', 'Play''n GO'),
('The Sword and the Grail', 'Play''n GO'),
('Wild Blood', 'Play''n GO'),
('Wild Blood 2', 'Play''n GO'),
('Wild Falls', 'Play''n GO'),
('Wild Frames', 'Play''n GO'),
('Wild North', 'Play''n GO'),
('Wild Rails', 'Play''n GO'),
('Wildhound Derby', 'Play''n GO'),
('Win a Beest', 'Play''n GO'),
('Book of Dead', 'Play''n GO'),
('Perfect Gems', 'Play''n GO'),
('Moon Princess 100', 'Play''n GO'),
('Coils of Cash', 'Play''n GO'),
('Sizzling Spins', 'Play''n GO'),
('Aztec Warrior Princess', 'Play''n GO'),
('Amulet of Dead', 'Play''n GO'),
('The Green Knight', 'Play''n GO'),
('Prism of Gems', 'Play''n GO'),
('3 Clown Monty', 'Play''n GO'),
('Court of Hearts', 'Play''n GO'),
('Hammerfall', 'Play''n GO'),
('Fire Toad', 'Play''n GO'),
('Scroll of Dead', 'Play''n GO'),
('Charlie CHance XREELZ', 'Play''n GO'),
('Candy Island Princess', 'Play''n GO'),
('Free Reelin'' Joker', 'Play''n GO'),
('24K Dragon', 'Play''n GO'),
('Lord Merlin and the Lady of the Lake', 'Play''n GO'),
('Miner Donkey Trouble', 'Play''n GO'),
('Bull in a China Shop', 'Play''n GO'),
('Shimmering Woods', 'Play''n GO'),
('House of Doom 2', 'Play''n GO'),
('Piggy Bank Farm', 'Play''n GO'),
('Troll Hunters 2', 'Play''n GO'),
('Rabbit Hole Riches', 'Play''n GO'),
('The Playing Piano Club', 'Play''n GO'),
('Helloween', 'Play''n GO'),
('Fire Joker Freeze', 'Play''n GO'),
('The Faces of Freya', 'Play''n GO'),
('Annihilator', 'Play''n GO'),
('Rich of Robin', 'Play''n GO'),
('Golden Legend', 'Play''n GO'),
('Eclipse of the Sun God', 'Play''n GO'),
('Viking Runecraft', 'Play''n GO'),
('Pearl Lagoon', 'Play''n GO'),
('Sweet Alchemy Bingo', 'Play''n GO'),
('Prosperity Palace', 'Play''n GO'),
('Queens Day Tilt', 'Play''n GO'),
('Super Flip', 'Play''n GO'),
('Wizard of Gems', 'Play''n GO'),
('Sweet 27', 'Play''n GO'),
('Rage of Riches', 'Play''n GO'),
('5x Magic', 'Play''n GO'),
('Tower Quest', 'Play''n GO'),
('Troll Hunters', 'Play''n GO'),
('Space Race', 'Play''n GO'),
('Jade Magician', 'Play''n GO'),
('Ninja Fruits', 'Play''n GO'),
('Agent Destiny', 'Play''n GO'),
('XMas Magic', 'Play''n GO'),
('XMas Joker', 'Play''n GO'),
('Spin Party', 'Play''n GO'),
('Sea Hunter', 'Play''n GO'),
('Rally 4 Riches', 'Play''n GO'),
('Happy Halloween', 'Play''n GO'),
('Enchanted Meadow', 'Play''n GO'),
('Prissy Princess', 'Play''n GO'),
('Ace of Spades', 'Play''n GO'),
('Enchanted Crystals', 'Play''n GO'),
('Easter Eggs', 'Play''n GO'),
('Golden Goal', 'Play''n GO'),
('Photo Safari', 'Play''n GO'),
('Wild Melon', 'Play''n GO'),
('Speed Cash', 'Play''n GO'),
('Bell of Fortune', 'Play''n GO'),
('Bakers Treat', 'Play''n GO'),
('Muerto En Mictlan', 'Play''n Go'),
('Alice Coopler', 'Play''n Go'),
('Ghost of Dead', 'Play''n Go'),
('Agent of Hearts', 'Play''n Go'),
('Hotel Yeti', 'Play''n Go'),
('Hooligan Hustle', 'Play''n Go'),
('Diamonds Of The Realm', 'Play''n Go'),
('Captain Xeno''s Earth Adventure', 'Play''n Go'),
('The Wild Class', 'Play''n Go'),
('Wandering City', 'Play''n Go'),
('Freya''s Wedding', 'Play''n Go'),
('Hugo Carts', 'Play''n Go'),
('Eye of Atum', 'Play''n Go'),
('Fat Frankies', 'Play''n Go'),
('King''s Mask', 'Play''n Go'),
('Odin Protector of Realms', 'Play''n GO'),
('Pilgrim Of Dead', 'Play''n GO'),
('Slashimi', 'Play''n GO'),
('Boat Bonanza Colossal Catch', 'Play''n GO'),
('Honey Rush 100', 'Play''n GO'),
('Honey Rush (1x 1x 1x)', 'Play''n GO'),
('Honey Rush (1x 1x 2x)', 'Play''n GO'),
('Honey Rush (1x 1x 3x)', 'Play''n GO'),
('Honey Rush (1x 2x 2x)', 'Play''n GO'),
('Honey Rush (1x 2x 3x)', 'Play''n GO'),
('Honey Rush (1x 3x 3x)', 'Play''n GO'),
('Honey Rush (2x 2x 3x)', 'Play''n GO'),
('Honey Rush (2x 3x 3x)', 'Play''n GO'),
('Honey Rush (3x 3x 3x)', 'Play''n GO'),
('Honey Rush (2x 2x 2x)', 'Play''n GO'),
('Rise of Olympus 100', 'Play''n GO'),
('Alice Cooper and the Tome of Madness', 'Play''n GO'),
('Big Bass Bonanza', 'Pragmatic Play'),
('Mayan Gods', 'Pragmatic Play'),
('Spartan King', 'Pragmatic Play'),
('Christmas Carol Megaways', 'Pragmatic Play'),
('Cowboys Gold', 'Pragmatic Play'),
('Book of Kingdoms', 'Pragmatic Play'),
('Pirate Gold Deluxe', 'Pragmatic Play'),
('Dragon Tiger', 'Pragmatic Play'),
('Gems Bonanza', 'Pragmatic Play'),
('Return of the Dead', 'Pragmatic Play'),
('5 Lions Dance', 'Pragmatic Play'),
('Emerald King', 'Pragmatic Play'),
('Wild Walker', 'Pragmatic Play'),
('Wild Wild Riches', 'Pragmatic Play'),
('Star Bounty', 'Pragmatic Play'),
('Curse of the Werewolf', 'Pragmatic Play'),
('Peaky Blinders', 'Pragmatic Play'),
('Jungle Gorilla', 'Pragmatic Play'),
('The Dog House Megaways', 'Pragmatic Play'),
('Aztec Gems Deluxe', 'Pragmatic Play'),
('Great Rhino Deluxe', 'Pragmatic Play'),
('Street Racer', 'Pragmatic Play'),
('Drago', 'Pragmatic Play'),
('Pyramid King', 'Pragmatic Play'),
('Three Star Fortune', 'Pragmatic Play'),
('Starz Megaways', 'Pragmatic Play'),
('Ultra Burn', 'Pragmatic Play'),
('Fruit Party', 'Pragmatic Play'),
('Hot to Burn', 'Pragmatic Play'),
('Book of Tut', 'Pragmatic Play'),
('Great Rhino Megaways', 'Pragmatic Play'),
('Bronco Spirit', 'Pragmatic Play'),
('Fruit Rainbow', 'Pragmatic Play'),
('Wild West Gold', 'Pragmatic Play'),
('Dance Party', 'Pragmatic Play'),
('The Wild Machine', 'Pragmatic Play'),
('Aztec Bonanza', 'Pragmatic Play'),
('Golden Beauty', 'Pragmatic Play'),
('Mysterious', 'Pragmatic Play'),
('Master Joker', 'Pragmatic Play'),
('Super 7''s', 'Pragmatic Play'),
('Release the Kraken', 'Pragmatic Play'),
('Money Mouse', 'Pragmatic Play'),
('Magic Journey', 'Pragmatic Play'),
('Buffalo King', 'Pragmatic Play'),
('Greek Gods', 'Pragmatic Play'),
('Sweet Bonanza Xmas', 'Pragmatic Play'),
('Hercules and Pegasus', 'Pragmatic Play'),
('Aladdin and the Sorcerer', 'Pragmatic Play'),
('Honey Honey Honey', 'Pragmatic Play'),
('Fire Strike', 'Pragmatic Play'),
('Tree of Riches', 'Pragmatic Play'),
('Scarab Queen', 'Pragmatic Play'),
('Super Joker', 'Pragmatic Play'),
('The Great Chicken Escape', 'Pragmatic Play'),
('Vampire vs Wolves', 'Pragmatic Play'),
('Hot Chilli', 'Pragmatic Play'),
('Aztec Treasure', 'Pragmatic Play'),
('Monkey Warrior', 'Pragmatic Play'),
('Sweet Bonanza', 'Pragmatic Play'),
('5 Lions Gold', 'Pragmatic Play'),
('Triple Jokers', 'Pragmatic Play'),
('Pirate Gold', 'Pragmatic Play'),
('Caishen''s Cash', 'Pragmatic Play'),
('The Dog House', 'Pragmatic Play'),
('Egyptian Fortunes', 'Pragmatic Play'),
('WIld Pixies', 'Pragmatic Play'),
('Extra Juicy', 'Pragmatic Play'),
('Wild Gladiators', 'Pragmatic Play'),
('Safari King', 'Pragmatic Play'),
('Treasure Horse', 'Pragmatic Play'),
('Mustang Gold', 'Pragmatic Play'),
('Leprechaun Carol', 'Pragmatic Play'),
('Triple Dragons', 'Pragmatic Play'),
('Ancient Egypt Classic', 'Pragmatic Play'),
('Vegans Magic', 'Pragmatic Play'),
('Master Chen''s Fortune', 'Pragmatic Play'),
('Da Vinci''s Treasure', 'Pragmatic Play'),
('Leprechaun Song', 'Pragmatic Play'),
('Peking Luck', 'Pragmatic Play'),
('Jade Butterfly', 'Pragmatic Play'),
('Madame Destiny', 'Pragmatic Play'),
('Asgard', 'Pragmatic Play'),
('The Champions', 'Pragmatic Play'),
('5 Lions', 'Pragmatic Play'),
('Great Rhino', 'Pragmatic Play'),
('Joker''s Jewels', 'Pragmatic Play'),
('Fire 88', 'Pragmatic Play'),
('Fairytale Fortune', 'Pragmatic Play'),
('Aztec Gems', 'Pragmatic Play'),
('Ancient Egypt', 'Pragmatic Play'),
('Lucky New Year', 'Pragmatic Play'),
('Chilli Heat', 'Pragmatic Play'),
('Monkey Madness', 'Pragmatic Play'),
('Triple Tigers', 'Pragmatic Play'),
('Santa', 'Pragmatic Play'),
('Panda''s Fortune', 'Pragmatic Play'),
('7 Piggies', 'Pragmatic Play'),
('Diamond Strike', 'Pragmatic Play'),
('Vegas Nights', 'Pragmatic Play'),
('Wild Spells', 'Pragmatic Play'),
('Caishen''s Gold', 'Pragmatic Play'),
('Pixie Wings', 'Pragmatic Play'),
('Jurassic Giants', 'Pragmatic Play'),
('Wolf Gold', 'Pragmatic Play'),
('888 Dragons', 'Pragmatic Play'),
('8 Dragons', 'Pragmatic Play'),
('Gold Train', 'Pragmatic Play'),
('3 Kingdoms', 'Pragmatic Play'),
('Queen of Gold', 'Pragmatic Play'),
('Hot Safari', 'Pragmatic Play'),
('Panther Queen', 'Pragmatic Play'),
('Queen of Atlantis', 'Pragmatic Play'),
('Irish Charms', 'Pragmatic Play'),
('888 Gold', 'Pragmatic Play'),
('Hercules Son of Zeus', 'Pragmatic Play'),
('Dragon Kingdom', 'Pragmatic Play'),
('3 Genie Wishes', 'Pragmatic Play'),
('Journey to the West', 'Pragmatic Play'),
('Beowulf', 'Pragmatic Play'),
('Lucky Dragons', 'Pragmatic Play'),
('Diamonds are Forever 3 Lines', 'Pragmatic Play'),
('The Catfather Part II', 'Pragmatic Play'),
('Dwarven Gold Deluxe', 'Pragmatic Play'),
('Romeo and Juliet', 'Pragmatic Play'),
('7 Monkeys', 'Pragmatic Play'),
('Hockey League Wild Match', 'Pragmatic Play'),
('Mighty Kong', 'Pragmatic Play'),
('Lady Godiva', 'Pragmatic Play'),
('The Catfather', 'Pragmatic Play'),
('Magic Crystals', 'Pragmatic Play'),
('Hockey League', 'Pragmatic Play'),
('Aladdin''s Treasure', 'Pragmatic Play'),
('Lady of the Moon', 'Pragmatic Play'),
('Sugar Rush', 'Pragmatic Play'),
('Dwarven Gold', 'Pragmatic Play'),
('Glorious Rome', 'Pragmatic Play'),
('Great Reef', 'Pragmatic Play'),
('Tales of Egypt', 'Pragmatic Play'),
('Gates of Olympus', 'Pragmatic Play'),
('Mysterious Egypt', 'Pragmatic Play'),
('Power of Thor MW', 'Pragmatic Play'),
('The Hand of Midas', 'Pragmatic Play'),
('Juicy Fruits', 'Pragmatic Play'),
('Madame Destiny MW', 'Pragmatic Play'),
('Voodoo Magic', 'Pragmatic Play'),
('Floating Dragon', 'Pragmatic Play'),
('Dragon Hot H&W', 'Pragmatic Play'),
('5 Lions MW', 'Pragmatic Play'),
('Chicken Drop', 'Pragmatic Play'),
('Hot Fiesta', 'Pragmatic Play'),
('Fruit Party 2', 'Pragmatic Play'),
('Treasure Wilds', 'Pragmatic Play'),
('Bigger Bass Bonanza', 'Pragmatic Play'),
('Starlight Princess', 'Pragmatic Play'),
('Day of Dead', 'Pragmatic Play'),
('Bounty Gold', 'Pragmatic Play'),
('Temujin Treasures', 'Pragmatic Play'),
('Wild Booster', 'Pragmatic Play'),
('Empty the Bank', 'Pragmatic Play'),
('Christmas Bass Bonanza', 'Pragmatic Play'),
('Santas Wonderland', 'Pragmatic Play'),
('Quest for Bermuda Riches', 'Pragmatic Play'),
('Big Bass Bonanza MW', 'Pragmatic Play'),
('Book of Fallen', 'Pragmatic Play'),
('Smugglers Cove', 'Pragmatic Play'),
('Book of Vikings', 'Pragmatic Play'),
('Gates of Valhalla', 'Pragmatic Play'),
('Big Bass Splash', 'Pragmatic Play'),
('Extra Juicy Megaways', 'Pragmatic Play'),
('Rock Vegas', 'Pragmatic Play'),
('Book of Golden Sands', 'Pragmatic Play'),
('Wild Hop n Drop', 'Pragmatic Play'),
('Muertos Multiplier Megaways', 'Pragmatic Play'),
('Sword of Ares', 'Pragmatic Play'),
('Shield of Sparta', 'Pragmatic Play'),
('The Dog Mansion', 'Pragmatic Play'),
('Pinup Girls', 'Pragmatic Play'),
('Fire Archer', 'Pragmatic Play'),
('Floating Dragon Megaways', 'Pragmatic Play'),
('Wild West Duels', 'Pragmatic Play'),
('Big Bass - Keeping it Real', 'Pragmatic Play'),
('The Dog House Multihold', 'Pragmatic Play'),
('The Dog House Dice Show', 'Pragmatic Play'),
('Wild West Gold Megaways', 'Pragmatic Play'),
('Goblin Heist', 'Pragmatic Play'),
('Floating Dragon - Dragon Boat Festival', 'Pragmatic Play'),
('Big Bass Amazon Extreme', 'Pragmatic Play'),
('Cleocatra', 'Pragmatic Play'),
('Big Bass Blizzard', 'Pragmatic Play'),
('Pirate Golden Age', 'Pragmatic Play'),
('Magician''s Secrets', 'Pragmatic Play'),
('Sweet Bonanza Dice', 'Pragmatic Play'),
('Heist for the Golden Nuggets', 'Pragmatic Play'),
('Power of Merlin Megaways', 'Pragmatic Play'),
('Candy Stars', 'Pragmatic Play'),
('3 Buzzing Wilds', 'Pragmatic Play'),
('Sky Bounty', 'Pragmatic Play'),
('Sticky Bees', 'Pragmatic Play'),
('Zombie Carnival', 'Pragmatic Play'),
('Dragon Hero', 'Pragmatic Play'),
('Big Bass Halloween', 'Pragmatic Play'),
('Infective Wilds', 'Pragmatic Play'),
('Starlight Christmas', 'Pragmatic Play'),
('Chase For Glory', 'Pragmatic Play'),
('Santa''s Wonderland', 'Pragmatic Play'),
('Wild Beach Party', 'Pragmatic Play'),
('Gates of Olympus 1000', 'Pragmatic Play'),
('Zeus Vs Hades', 'Pragmatic Play'),
('Roo Bonanza', 'Pragmatic Play'),
('Starlight Princess 1000', 'Pragmatic Play'),
('Juicy Fruits Multihold', 'Pragmatic Play'),
('Ding Dong', 'Pragmatic Play'),
('Big Bass Christmas Bash', 'Pragmatic Play'),
('Twilight Princess', 'Pragmatic Play'),
('Floating Dragon New Year Festival Ultra Megaways Hold & Spin', 'Pragmatic Play'),
('Big Bass Bonanza Hold & Spinner MW', 'Pragmatic Play'),
('The Wild Gang', 'Pragmatic Play'),
('Santa''s Great Gift', 'Pragmatic Play'),
('Year of the Dragon King', 'Pragmatic Play'),
('The Big Dawgs', 'Pragmatic Play'),
('Release the Kraken 2', 'Pragmatic Play'),
('Jewel rush', 'Pragmatic Play'),
('Fire portals', 'Pragmatic Play'),
('zues vs hades', 'Pragmatic Play'),
('Da Vinci''s Treasure (Progressive)', 'Pragmatic Play'),
('Big Bass Bonanza Hold & Spinner', 'Pragmatic Play'),
('Hotline 2', 'NetEnt'),
('Aloha! Cluster Pays', 'NetEnt'),
('Arabian Nights', 'NetEnt'),
('Arcane: Reel Chaos', 'NetEnt'),
('Archangels: Salvation', 'NetEnt'),
('Asgardian Stones', 'NetEnt'),
('Berryburst', 'NetEnt'),
('Blood Suckers', 'NetEnt'),
('Blood Suckers 2', 'NetEnt'),
('Bollywood Story', 'NetEnt'),
('Butterfly Staxx', 'NetEnt'),
('Butterfly Staxx 2', 'NetEnt'),
('Cash-O-Matic', 'NetEnt'),
('Coins of Egypt', 'NetEnt'),
('Conan', 'NetEnt'),
('Copy Cats', 'NetEnt'),
('Cosmic Fortune', 'NetEnt'),
('Dazzle Me', 'NetEnt'),
('Dead or Alive', 'NetEnt'),
('Dead or Alive 2', 'NetEnt'),
('Divine Fortune', 'NetEnt'),
('Double Stacks', 'NetEnt'),
('Dracula', 'NetEnt'),
('Drive', 'NetEnt'),
('Druids'' Dream', 'NetEnt'),
('EggOMatic', 'NetEnt'),
('Elements', 'NetEnt'),
('Emoji Planet', 'NetEnt'),
('Excalibur', 'NetEnt'),
('Finn and the Swirly Spin', 'NetEnt'),
('Finn''s Golden Tavern', 'NetEnt'),
('Flowers', 'NetEnt'),
('Flowers Christmas', 'NetEnt'),
('Football: Champions Cup', 'NetEnt'),
('Fortune Rangers', 'NetEnt'),
('Fruit Case', 'NetEnt'),
('Fruit Shop', 'NetEnt'),
('Fruit Shop Christmas', 'NetEnt'),
('Fruit Spin', 'NetEnt'),
('Ghost Pirates', 'NetEnt'),
('Go Bananas', 'NetEnt'),
('Golden Grimoire', 'NetEnt'),
('Gonzo''s Quest', 'NetEnt'),
('Grand Spinn', 'NetEnt'),
('Grand Spinn Superpot', 'NetEnt'),
('Guns N'' Roses', 'NetEnt'),
('Hall of Gods', 'NetEnt'),
('Halloween Jack', 'NetEnt'),
('Hansel and Gretel', 'NetEnt'),
('Hook''s Heroes', 'NetEnt'),
('Hotline', 'NetEnt'),
('Imperial Riches', 'NetEnt'),
('Jack Hammer', 'NetEnt'),
('Jack Hammer 2', 'NetEnt'),
('Jack and the Beanstalk', 'NetEnt'),
('Jackpot 6000', 'NetEnt'),
('Jacks or Better Double Up', 'NetEnt'),
('Jimi Hendrix', 'NetEnt'),
('Jingle Spin', 'NetEnt'),
('Joker Pro', 'NetEnt'),
('Jumanji', 'NetEnt'),
('Jungle Spirit', 'NetEnt'),
('King of 3 Kingdoms', 'NetEnt'),
('Koi Princess', 'NetEnt'),
('König der Slots', 'NetEnt'),
('Lights', 'NetEnt'),
('Long Pao', 'NetEnt'),
('Lost Relics', 'NetEnt'),
('Lucky Angler', 'NetEnt'),
('Magic Portals', 'NetEnt'),
('Mega Fortune', 'NetEnt'),
('Mega Fortune Dreams', 'NetEnt'),
('Mega Joker', 'NetEnt'),
('Mercy of the Gods', 'NetEnt'),
('Mirror Mirror', 'NetEnt'),
('Motörhead', 'NetEnt'),
('Mythic Maiden', 'NetEnt'),
('Narcos', 'NetEnt'),
('Neon Staxx', 'NetEnt'),
('Ocean''s Treasure', 'NetEnt'),
('Ozzy Osbourne', 'NetEnt'),
('Piggy Riches', 'NetEnt'),
('Pirate from the East', 'NetEnt'),
('Planet of the Apes', 'NetEnt'),
('Pyramid', 'NetEnt'),
('Red Riding Hood', 'NetEnt'),
('Reel Rush', 'NetEnt'),
('Reel Rush 2', 'NetEnt'),
('Rise of Maya', 'NetEnt'),
('Robin Hood', 'NetEnt'),
('Robin Hood -Shifting Riches Slot', 'NetEnt'),
('Santa vs Rudolf', 'NetEnt'),
('Scruffy Duck', 'NetEnt'),
('Scudamore''s Super Stakes', 'NetEnt'),
('Secret of the Stones', 'NetEnt'),
('Secrets of Atlantis', 'NetEnt'),
('Secrets of Christmas', 'NetEnt'),
('Serengeti Kings', 'NetEnt'),
('Shangri La', 'NetEnt'),
('Space Wars', 'NetEnt'),
('Sparks', 'NetEnt'),
('Spellcast', 'NetEnt'),
('Spinata Grande', 'NetEnt'),
('Spinsane', 'NetEnt'),
('Starburst', 'NetEnt'),
('Steam Tower', 'NetEnt'),
('Stickers', 'NetEnt'),
('Strolling Staxx', 'NetEnt'),
('Super Lucky Frog', 'NetEnt'),
('Swipe and Roll', 'NetEnt'),
('Temple of Nudges', 'NetEnt'),
('The Invisible Man', 'NetEnt'),
('The Phantom''s Curse', 'NetEnt'),
('The Reel Steal', 'NetEnt'),
('The Wish Master', 'NetEnt'),
('The Wolf''s Bane', 'NetEnt'),
('Theme Park', 'NetEnt'),
('Turn Your Fortune', 'NetEnt'),
('Twin Happiness', 'NetEnt'),
('Twin Spin', 'NetEnt'),
('Twin Spin Deluxe', 'NetEnt'),
('Victorious', 'NetEnt'),
('Victorious MAX', 'NetEnt'),
('Vikings', 'NetEnt'),
('Warlords', 'NetEnt'),
('Who''s the Bride', 'NetEnt'),
('Wild Bazaar', 'NetEnt'),
('Wild Rockets', 'NetEnt'),
('Wild Turkey', 'NetEnt'),
('Wild Water', 'NetEnt'),
('Wild Wild West', 'NetEnt'),
('Wild Worlds', 'NetEnt'),
('Wild-O-Tron 3000', 'NetEnt'),
('Wilderland', 'NetEnt'),
('Wings of Riches', 'NetEnt'),
('Witchcraft Academy', 'NetEnt'),
('Wolf Cub', 'NetEnt'),
('Wonky Wabbits', 'NetEnt'),
('Regal Streak', 'Red Tiger'),
('Thors Vengeance', 'Red Tiger'),
('Devil''s Number', 'Red Tiger'),
('Gonzos Quest Mega Ways', 'Red Tiger'),
('Dynamite Riches', 'Red Tiger'),
('Piggy Riches Mega Ways', 'Red Tiger'),
('Dragons Fire Mega Ways', 'Red Tiger'),
('Pirates Plenty Battle for Gold', 'Red Tiger'),
('Zeus Lightning Power Reels', 'Red Tiger'),
('Crazy Genie', 'Red Tiger'),
('Dragons Luck', 'Red Tiger'),
('Da Vincis Mystery', 'Red Tiger'),
('Grand Wheel', 'Red Tiger'),
('Phoenix Fire Power Reels', 'Red Tiger'),
('Dragons Luck Power Reels', 'Red Tiger'),
('Golden Leprechaun Mega Ways', 'Red Tiger'),
('Dragons Fire', 'Red Tiger'),
('Wild Cats Multiline', 'Red Tiger'),
('Ninja Ways', 'Red Tiger'),
('Vault Of Anubis', 'Red Tiger'),
('Red Diamond', 'Red Tiger'),
('Pirates Plenty', 'Red Tiger'),
('Reel King Mega', 'Red Tiger'),
('Lucky Oktoberfest', 'Red Tiger'),
('Mystery Reels Mega Ways', 'Red Tiger'),
('Lucky Halloween', 'Red Tiger'),
('Rocket Men', 'Red Tiger'),
('Treasure Mine', 'Red Tiger'),
('Jewel Scarabs', 'Red Tiger'),
('24 Hour Grand Prix', 'Red Tiger'),
('Persian Fortune', 'Red Tiger'),
('Wings of Ra', 'Red Tiger'),
('Dragons Luck Mega Ways', 'Red Tiger'),
('Gems Gone Wild', 'Red Tiger'),
('Spin Town', 'Red Tiger'),
('Well of Wishes', 'Red Tiger'),
('Jackpot Quest', 'Red Tiger'),
('Lucky Little Devil', 'Red Tiger'),
('Mystery Reels', 'Red Tiger'),
('Mega Pyramid', 'Red Tiger'),
('Cirque De La Fortune', 'Red Tiger'),
('Laser Fruit', 'Red Tiger'),
('The Greatest Train Robbery', 'Red Tiger'),
('Rio Stars', 'Red Tiger'),
('Cash Volt', 'Red Tiger'),
('Eagle Riches', 'Red Tiger'),
('Golden Tsar', 'Red Tiger'),
('Wild Fight', 'Red Tiger'),
('Wild Wild Chest', 'Red Tiger'),
('Esqueleto Mariachi', 'Red Tiger'),
('Mega Dragon', 'Red Tiger'),
('Thor''s Lightning', 'Red Tiger'),
('Bombuster', 'Red Tiger'),
('Lucky Wizard', 'Red Tiger'),
('Flaming Fox', 'Red Tiger'),
('Fortune Fest', 'Red Tiger'),
('Rainbow Jackpots Power Lines', 'Red Tiger'),
('Ancient Script', 'Red Tiger'),
('RA''s Legend', 'Red Tiger'),
('Mystery Reels Power Reels', 'Red Tiger'),
('Blue Diamond', 'Red Tiger'),
('Legendary Excalibus', 'Red Tiger'),
('Dice Dice Dice', 'Red Tiger'),
('Magic Gate', 'Red Tiger'),
('Gold Star', 'Red Tiger'),
('Wild Spartans', 'Red Tiger'),
('Wild Circus', 'Red Tiger'),
('Sumo Spins', 'Red Tiger'),
('Puss N Boots', 'Red Tiger'),
('Atlantis', 'Red Tiger'),
('Totem Lightning Power Reels', 'Red Tiger'),
('Snow Wild and the 7 Features', 'Red Tiger'),
('Rainbow Jackpots', 'Red Tiger'),
('Mega Rise', 'Red Tiger'),
('Piggy Pirates', 'Red Tiger'),
('Wild O''Clock', 'Red Tiger'),
('Chinese Treasures', 'Red Tiger'),
('5 Gamilies', 'Red Tiger'),
('Vicky Ventura', 'Red Tiger'),
('Win Escalator', 'Red Tiger'),
('Tiki Fruits', 'Red Tiger'),
('Wild Elements', 'Red Tiger'),
('Winter Wonders', 'Red Tiger'),
('Reel Heist', 'Red Tiger'),
('Three Musketeers', 'Red Tiger'),
('Fruit Blox', 'Red Tiger'),
('Fortune Charm', 'Red Tiger'),
('Golden Offer', 'Red Tiger'),
('Midas Gold', 'Red Tiger'),
('Arcade Bomb', 'Red Tiger'),
('Reactor', 'Red Tiger'),
('Masquerade', 'Red Tiger'),
('Aurum Codex', 'Red Tiger'),
('Elven Magic', 'Red Tiger'),
('Mayan Gods', 'Red Tiger'),
('Lucky Easter', 'Red Tiger'),
('Cinderella''s Ball', 'Red Tiger'),
('Totem Lightning', 'Red Tiger'),
('Crystal Mirror', 'Red Tiger'),
('Stage 888', 'Red Tiger'),
('Jack in a Pot', 'Red Tiger'),
('Jingle Bells', 'Red Tiger'),
('Golden Lotus', 'Red Tiger'),
('Lucky Valentine', 'Red Tiger'),
('Ten Elements', 'Red Tiger'),
('God of Wealth', 'Red Tiger'),
('Epic Journey', 'Red Tiger'),
('Emerald Diamond', 'Red Tiger'),
('Gems Gone Wild Power Reels', 'Red Tiger'),
('Divine Ways', 'Red Tiger'),
('Three Kingdoms', 'Red Tiger'),
('Jester Spins', 'Red Tiger'),
('Ocean Fortune', 'Red Tiger'),
('The Equalizer', 'Red Tiger'),
('Wild Nords', 'Red Tiger'),
('Fruit Snap', 'Red Tiger'),
('Five Star Power Reels', 'Red Tiger'),
('Imperial Palace', 'Red Tiger'),
('Royal Gems', 'Red Tiger'),
('Lucky Fridays', 'Red Tiger'),
('Mega Jade', 'Red Tiger'),
('Jade Charms', 'Red Tiger'),
('Gemtastic', 'Red Tiger'),
('Five Star', 'Red Tiger'),
('Red Phoenix Rising', 'Red Tiger'),
('Golden Temple', 'Red Tiger'),
('Hoard of Poseidon', 'Red Tiger'),
('Diamond Blitz', 'Red Tiger'),
('Golden Cryptex', 'Red Tiger'),
('Lucky Mr Green', 'Red Tiger'),
('Phoenix', 'Red Tiger'),
('The Wild Hatter', 'Red Tiger'),
('Aztec Spins', 'Red Tiger'),
('Lucky Fortune Cat', 'Red Tiger'),
('Robin Hood Wild Forest', 'Red Tiger'),
('4 Squad', 'Red Tiger'),
('Bounty Raid', 'Red Tiger'),
('Captain Rizk Mega Ways', 'Red Tiger'),
('Multiplier Riches', 'Red Tiger'),
('Reel Keeper', 'Red Tiger'),
('Kulta Jaska Mega Ways', 'Red Tiger'),
('Lord of the Wilds', 'Red Tiger'),
('Joe exotic', 'Red Tiger'),
('It''s Time', 'Relax Gaming'),
('Aztec Luck', 'Relax Gaming'),
('Kluster Krystals', 'Relax Gaming'),
('Money Train 2', 'Relax Gaming'),
('Money Train', 'Relax Gaming'),
('Snake Arena', 'Relax Gaming'),
('Iron Bank', 'Relax Gaming'),
('Hellcatraz', 'Relax Gaming'),
('Temple Tumble', 'Relax Gaming'),
('TnT Tumble', 'Relax Gaming'),
('Marching Legions', 'Relax Gaming'),
('Let''s Get Ready To Rumble', 'Relax Gaming'),
('Mega Masks', 'Relax Gaming'),
('Ramses Revenge', 'Relax Gaming'),
('Epic Joker', 'Relax Gaming'),
('Tower Tumble', 'Relax Gaming'),
('Super Boost', 'Relax Gaming'),
('Dragon''s Awakening', 'Relax Gaming'),
('King of Kings', 'Relax Gaming'),
('Heroes'' Gathering', 'Relax Gaming'),
('The Great Pigsby', 'Relax Gaming'),
('La Fiesta', 'Relax Gaming'),
('Frequent Flyer', 'Relax Gaming'),
('Caveman Bob', 'Relax Gaming'),
('Zombie Circus', 'Relax Gaming'),
('Erik the Red', 'Relax Gaming'),
('Mega Flip', 'Relax Gaming'),
('Wildchemy', 'Relax Gaming'),
('Powerspin', 'Relax Gaming'),
('Hypernova MW', 'Relax Gaming'),
('Spirit of the Beast', 'Relax Gaming'),
('Volatile Vikings', 'Relax Gaming'),
('Cluster Tumble', 'Relax Gaming'),
('Templar Tumble', 'Relax Gaming'),
('Santas Stack', 'Relax Gaming'),
('Wild Chapo', 'Relax Gaming'),
('Dead Man''s Trail', 'Relax Gaming'),
('Royal Potato', 'Relax Gaming'),
('Beast Mode', 'Relax Gaming'),
('Book of Power', 'Relax Gaming'),
('Space Miners', 'Relax Gaming'),
('Helios Fury', 'Relax Gaming'),
('Wild Hike', 'Relax Gaming'),
('Net Gains', 'Relax Gaming'),
('Its Time', 'Relax Gaming'),
('Santa''s Stack', 'Relax Gaming'),
('Gems Of The Gods', 'Push Gaming'),
('Golden Farm', 'Push Gaming'),
('Meet the Meerkats', 'Push Gaming'),
('The Hidden Temple', 'Push Gaming'),
('Jammin'' Jars', 'Push Gaming'),
('Razor Shark', 'Push Gaming'),
('Fat Santa', 'Push Gaming'),
('Wild Swarm', 'Push Gaming'),
('Viking Clash', 'Push Gaming'),
('Mystery Museum', 'Push Gaming'),
('Fat Rabbit', 'Push Gaming'),
('Wild Wheel', 'Push Gaming'),
('Blaze of Ra', 'Push Gaming'),
('Tiki Tumble', 'Push Gaming'),
('The Shadow Order', 'Push Gaming'),
('Wizard Shop', 'Push Gaming'),
('Immortal Guild', 'Push Gaming'),
('Turn It Up', 'Push Gaming'),
('Ice Breaker', 'Push Gaming'),
('Dragon Sisters', 'Push Gaming'),
('Power Force Villains', 'Push Gaming'),
('Power Force Heroes', 'Push Gaming'),
('Bonus Beans', 'Push Gaming'),
('Hockey Hero', 'Push Gaming'),
('Wild Neon', 'Push Gaming'),
('Peter And The Lost Boys', 'Push Gaming'),
('Humpty Dumpty', 'Push Gaming'),
('Star Fall', 'Push Gaming'),
('Ultimate Dream Team', 'Push Gaming'),
('Jammin'' Jars 2', 'Push Gaming'),
('Dinopolis', 'Push Gaming'),
('Wheel of Wonders', 'Push Gaming'),
('Land of Zenith', 'Push Gaming'),
('Booty Bay', 'Push Gaming'),
('Fat Drac', 'Push Gaming'),
('Big Bamboo', 'Push Gaming'),
('Big Bamboo (Super)', 'Push Gaming'),
('Nightfall', 'Push Gaming'),
('Mystery Mission to the Moon', 'Push Gaming'),
('Retro Tapes', 'Push Gaming'),
('Joker Troupe', 'Push Gaming'),
('Fire Hopper', 'Push Gaming'),
('Crystal Catcher', 'Push Gaming'),
('Razor Returns', 'Push Gaming'),
('Deadly 5', 'Push Gaming'),
('Giga Jar', 'Push Gaming'),
('Goat Getter', 'Push Gaming'),
('Mayan Magic Wildfire', 'No Limit City'),
('Owls', 'No Limit City'),
('Casino Win Spin', 'No Limit City'),
('KD: BBQ Frenzy', 'No Limit City'),
('Star Struck', 'No Limit City'),
('Deadwood', 'No Limit City'),
('Punk Rocker', 'No Limit City'),
('Warrior Graveyard', 'No Limit City'),
('Book of Shadows', 'No Limit City'),
('Tombstone', 'No Limit City'),
('Dragon Tribe', 'No Limit City'),
('Barbarian Fury', 'No Limit City'),
('Golden Genie And The Walking Wilds', 'No Limit City'),
('Bonus Bunnies', 'No Limit City'),
('Tomb Of Akhenaten', 'No Limit City'),
('Monkey''s Gold: xPays', 'No Limit City'),
('Hot Nudge', 'No Limit City'),
('Buffalo Hunter', 'No Limit City'),
('Milky Ways', 'No Limit City'),
('Tractor Beam', 'No Limit City'),
('The Creepy Carnival', 'No Limit City'),
('Tomb Of Nefertiti', 'No Limit City'),
('Pixies VS Pirates', 'No Limit City'),
('Gaelic Gold', 'No Limit City'),
('Dungeon Quest', 'No Limit City'),
('Coins Of Fortune', 'No Limit City'),
('Tesla Jolt', 'No Limit City'),
('KD: Sushi Mania', 'No Limit City'),
('Thor: Hammer TIme', 'No Limit City'),
('Poison Eve', 'No Limit City'),
('Oktoberfest', 'No Limit City'),
('Ice Ice Yeti', 'No Limit City'),
('Mahattan Goes Wild', 'No Limit City'),
('Immortal Fruits', 'No Limit City'),
('Wixx', 'No Limit City'),
('Hot 4 Cash', 'No Limit City'),
('Fruits', 'No Limit City'),
('Fire in the Hole', 'No Limit City'),
('San Quentin', 'No Limit City'),
('El Paso', 'No Limit City'),
('East Coast vs West Coast', 'No Limit City'),
('Bushido', 'No Limit City'),
('xWays Hoarder xSplit', 'No Limit City'),
('Mental', 'No Limit City'),
('Harlequin Carneval', 'No Limit City'),
('Legion X', 'No Limit City'),
('Infectious 5Xways', 'No Limit City'),
('Das xBoot', 'No Limit City'),
('True Grit Redemption', 'No Limit City'),
('Miami Multiplier', 'No Limit City'),
('Remember Gulag', 'No Limit City'),
('Karen Maneater', 'No Limit City'),
('Punk Toilet', 'No Limit City'),
('Creepy Carnival', 'No Limit City'),
('Rock Bottom', 'No Limit City'),
('Serial', 'No Limit City'),
('Dead Canary', 'No Limit City'),
('Tombstone R.I.P', 'No Limit City'),
('The Rave', 'No Limit City'),
('Folsom Prison', 'No Limit City'),
('The Crypt', 'No Limit City'),
('Disturbed', 'No Limit City'),
('Evil Goblins', 'No Limit City'),
('Nine to Five', 'No Limit City'),
('True Kult', 'No Limit City'),
('Pearl Harbour', 'No Limit City'),
('Ugliest Catch', 'No Limit City'),
('Land of the Free', 'No Limit City'),
('Fire in the Hole 2', 'No Limit City'),
('D Day', 'No Limit City'),
('Hit The Route', 'BGaming'),
('Fruit Million', 'BGaming'),
('All Lucky Clovers 20', 'BGaming'),
('All Lucky Clovers 40', 'BGaming'),
('All Lucky Clovers', 'BGaming'),
('Aztec Magic Deluxe', 'BGaming'),
('Fire Lightning', 'BGaming'),
('Four Lucky Clover', 'BGaming'),
('Elvis Frog In Vegas', 'BGaming'),
('Avalon: The Lost Kingdom', 'BGaming'),
('Platinum Lightning Deluxe', 'BGaming'),
('Spin and Spell', 'BGaming'),
('West Town', 'BGaming'),
('Deep Sea', 'BGaming'),
('Aztec Magic', 'BGaming'),
('Book Of Pyramids', 'BGaming'),
('Domnitors Deluxe', 'BGaming'),
('Lucky Lady''s Clover', 'BGaming'),
('Cherry Fiesta', 'BGaming'),
('Journey Flirt', 'BGaming'),
('Brave Viking', 'BGaming'),
('Bob''s Coffee Shop', 'BGaming'),
('Princess Royal', 'BGaming'),
('Scroll of Adventure', 'BGaming'),
('Lucky Blue', 'BGaming'),
('Mechanical Orange', 'BGaming'),
('Domnitors', 'BGaming'),
('Platinum Lightning', 'BGaming'),
('Fantasy Park', 'BGaming'),
('Crazy Starter', 'BGaming'),
('Hello Easter', 'BGaming'),
('Princess Of Sky', 'BGaming'),
('Slotomon Go', 'BGaming'),
('All Lucky Clovers 100', 'BGaming'),
('Desert Treasure', 'BGaming'),
('Hawaii Cocktails', 'BGaming'),
('Lucky Sweets', 'BGaming'),
('Lucky Lady Moom', 'BGaming'),
('Bonanza Billion Xmas', 'BGaming'),
('Book of Cats', 'BGaming'),
('Crystals Digger', 'Belatra'),
('Bonanza Billion', 'BGaming'),
('Birthday!', 'Elk Studios'),
('Sam on the Beach', 'Elk Studios'),
('Taco Brothers Saving Christmas', 'Elk Studios'),
('DJ Wild', 'Elk Studios'),
('Champions Goal', 'Elk Studios'),
('The Lab', 'Elk Studios'),
('Electric Sam', 'Elk Studios'),
('Io', 'Elk Studios'),
('Voodoo Gold', 'Elk Studios'),
('Black River Gold', 'Elk Studios'),
('Hit It Big', 'Elk Studios'),
('Cygnus', 'Elk Studios'),
('Crusader', 'Elk Studios'),
('Micro Knights', 'Elk Studios'),
('Ice Wold', 'Elk Studios'),
('Vegas Diamonds', 'Elk Studios'),
('Tahiti Gold', 'Elk Studios'),
('Chi', 'Elk Studios'),
('Visitors', 'Elk Studios'),
('Respin Circus', 'Elk Studios'),
('Katmandu Gold', 'Elk Studios'),
('Ecuador Gold', 'Elk Studios'),
('Lake''s Five', 'Elk Studios'),
('Route 777', 'Elk Studios'),
('Blood Lust', 'Elk Studios'),
('Diablo Reels', 'Elk Studios'),
('Win Win', 'Elk Studios'),
('Nitropolis', 'Elk Studios'),
('Hit It Hard', 'Elk Studios'),
('Grand Galore', 'Elk Studios'),
('Wild Toro', 'Elk Studios'),
('Wild Seas', 'Elk Studios'),
('Valkyrie', 'Elk Studios'),
('Dreamzone', 'Elk Studios'),
('Platooners', 'Elk Studios'),
('The Wiz', 'Elk Studios'),
('Poltava', 'Elk Studios'),
('Ivanhoe', 'Elk Studios'),
('Hongkong Tower', 'Elk Studios'),
('Kaiju', 'Elk Studios'),
('Joker Gems', 'Elk Studios'),
('Taco Brothers', 'Elk Studios'),
('Ho Ho Tower', 'Elk Studios'),
('Hidden', 'Elk Studios'),
('Bloopers', 'Elk Studios'),
('Pirots', 'ELk Gaming'),
('Stars of Orion', 'Elk Gaming'),
('Magicious', 'Thunderkick'),
('Sunset Delight', 'Thunderkick'),
('Turning Totems', 'Thunderkick'),
('Spectra', 'Thunderkick'),
('Well of Wonders', 'Thunderkick'),
('Toki Time', 'Thunderkick'),
('Flux', 'Thunderkick'),
('Frog Grog', 'Thunderkick'),
('Fruit Warp', 'Thunderkick'),
('Midas Golden Touch', 'Thunderkick'),
('Sword of Khans', 'Thunderkick'),
('Riders Of The Storm', 'Thunderkick'),
('Dragon Horn', 'Thunderkick'),
('Pink Elephants 2', 'Thunderkick'),
('The Falcon Huntress', 'Thunderkick'),
('Esqueleto Explosivo 2', 'Thunderkick'),
('Wild Heist at Peacock Manor', 'Thunderkick'),
('Carnival Queen', 'Thunderkick'),
('Kraken''s Lair', 'Thunderkick'),
('Flame Busters', 'Thunderkick'),
('Jin Chan''s Pond Of Riches', 'Thunderkick'),
('Beat The Beast: Cerberus'' Inferno', 'Thunderkick'),
('Beat The Beast: Griffins'' Gold', 'Thunderkick'),
('Rocket Fellas Inc', 'Thunderkick'),
('Beat The Beast: Quetzalcoatl''s Trial', 'Thunderkick'),
('Beat The Beast: Mighty Sphinx', 'Thunderkick'),
('Divine Lotus', 'Thunderkick'),
('1429 Uncharted Seas', 'Thunderkick'),
('Not Enough Kittens', 'Thunderkick'),
('Zoom', 'Thunderkick'),
('Raven''s Eye', 'Thunderkick'),
('Crystal Quest: Deep Jungle', 'Thunderkick'),
('Jaguar Temple', 'Thunderkick'),
('Bork The Berzerker', 'Thunderkick'),
('Arcader', 'Thunderkick'),
('Crystal Quest: Arcane Tower', 'Thunderkick'),
('Yeti Battle Of Greenhat Peak', 'Thunderkick'),
('Tiger Rush', 'Thunderkick'),
('Luchadora', 'Thunderkick'),
('Full Moon Romance', 'Thunderkick'),
('Babushkas', 'Thunderkick'),
('Birds On A Wire', 'Thunderkick'),
('Esqueleto Explosivo', 'Thunderkick'),
('The Rift', 'Thunderkick'),
('Barbershop: Uncut', 'Thunderkick'),
('Big Fin Bay', 'Thunderkick'),
('Baron Bloodmore and The Crimson Castle', 'Thunderkick'),
('Lava Lava', 'Thunderkick'),
('Rex The Hunt', 'Thunderkick'),
('Shifting Seas', 'Thunderkick'),
('Gods of Rock', 'Thunderkick'),
('Jiggly Cash', 'Thunderkick'),
('Beat the Beast: Kraken''s Lair', 'Thunderkick'),
('Supreme Fortune', 'Booongo'),
('Fruiterra Fortune', 'Booongo'),
('Sync Reels', 'Booongo'),
('Fruity Wild', 'Booongo'),
('Singles Day', 'Booongo'),
('Diego Fortune', 'Booongo'),
('Gnomes'' Gems', 'Booongo'),
('Secret Of Nefertiti', 'Booongo'),
('15 Dragon Pearls: Hold And Win', 'Booongo'),
('Tiger''s Gold: Hold And Win', 'Booongo'),
('Super Marble: Hold And Win', 'Booongo'),
('Dragon Pearls: Hold And Win', 'Booongo'),
('Olympian Gods', 'Booongo'),
('Buddha Fortune: Hold And Win', 'Booongo'),
('Aztec Sun: Hold And Win', 'Booongo'),
('Book Of Sun Multichance', 'Booongo'),
('Moon Sisters: Hold And Win', 'Booongo'),
('Book Of Sun', 'Booongo'),
('15 Golden Eggs', 'Booongo'),
('Scarab Temple', 'Booongo'),
('Halloween Witch', 'Booongo'),
('Sun Of Egypt 2', 'Booongo'),
('12 Animals', 'Booongo'),
('Thunder Of Olympus', 'Booongo'),
('Viking''s Gods Gold', 'Booongo'),
('Wild 888', 'Booongo'),
('88 Dragon', 'Booongo'),
('777 Gems Respin', 'Booongo'),
('Poisoned Apple 2', 'Booongo'),
('Vikings Winter', 'Booongo'),
('Scarab Riches', 'Booongo'),
('Goddes Of The Moon', 'Booongo'),
('88 WIld Dragon', 'Booongo'),
('African Spirit', 'Booongo'),
('Shen Long Mi Bao', 'Booongo'),
('Monkey Money', 'Booongo'),
('777 Gems', 'Booongo'),
('Secret Of Nefertiti 2', 'Booongo'),
('Age Of Caesar', 'Booongo'),
('Tiger Stone', 'Booongo'),
('Lucky Xmas', 'Booongo'),
('Fortune Multiplier', 'Booongo'),
('Fu Cai Shen', 'Booongo'),
('Sky Gems 5 Wilds', 'Booongo'),
('Thunder Zeus', 'Booongo'),
('God''s Temple Deluxe', 'Booongo'),
('Christmas Charm', 'Booongo'),
('Poisoned Apple', 'Booongo'),
('Eye Of Gold', 'Booongo'),
('God''s Temple', 'Booongo'),
('Beast Saga', 'Booongo'),
('Three Gems: Adjacent', 'Booongo'),
('Patrick''s Pub', 'Booongo'),
('Star Gems', 'Booongo'),
('Scarab Boost H&W', 'Booongo'),
('Wukong H&W', 'Booongo'),
('Candy  Boom', 'Booongo'),
('Windfall', 'Blueprint'),
('Lucky 8 Fortune Cat', 'Blueprint'),
('Mistress Of Fortune', 'Blueprint'),
('Jewel Strike', 'Blueprint'),
('Fortune Spins', 'Blueprint'),
('Hot Zone', 'Blueprint'),
('Lion Thunder', 'Blueprint'),
('Jewel Twist', 'Blueprint'),
('Candy Cascade', 'Blueprint'),
('Safari Gold Megaways', 'Blueprint'),
('Return Of The Kong Megaways', 'Blueprint'),
('Dragon Fall', 'Blueprint'),
('Vikings Unleashed Megaways', 'Blueprint'),
('Buffalo Rising Megaways', 'Blueprint'),
('Gorilla Gold Megaways', 'Blueprint'),
('Genie Jackpot Megaways', 'Blueprint'),
('Temple Of Treasure Megaways', 'Blueprint'),
('Primal Megaways', 'Blueprint'),
('Fishin Frenzy Megaways', 'Blueprint'),
('Napoleon', 'Blueprint'),
('Legacy Of Ra Megaways', 'Blueprint'),
('Wolf Legend Megaways', 'Blueprint'),
('Gods Of Olympus Megaways', 'Blueprint'),
('DIamond Mine Megaways', 'Blueprint'),
('Buffalo Rising Megaways All Action', 'Blueprint'),
('Diamond Mine Extra Gold All Actions', 'Blueprint'),
('Eye of Horus Megaways', 'Blueprint'),
('Fishin Frenzy', 'Blueprint'),
('Sweet Success Megaways', 'Blueprint'),
('Big Cat King Megaways', 'Blueprint'),
('Bar X Safe Cracker Megaways', 'Blueprint'),
('King Kong Cash', 'Blueprint'),
('Wish Upon A Jackpot', 'Blueprint'),
('Diamond Mine Extra Gold Megaways', 'Blueprint'),
('Lightning Strike Megaways', 'Blueprint'),
('Wish Upon A Leprechaun Megaways', 'Blueprint'),
('Fortunes Of Sparta', 'Blueprint'),
('Rome Rise Of An Empire', 'Blueprint'),
('Valletta Megaways', 'Blueprint'),
('Genie Jackpots Wishmaker', 'Blueprint'),
('El Jackpotto', 'Blueprint'),
('Luck Of The Irish Megaways', 'Blueprint'),
('Journey Of The Gods', 'Blueprint'),
('Wild Antics', 'Blueprint'),
('Fishin Frenzy Power 4 Slots', 'Blueprint'),
('Gun Slinger', 'Blueprint'),
('Jungle Jackpots', 'Blueprint'),
('Master Of Atlantis', 'Blueprint'),
('Kingdom Of Fortune', 'Blueprint'),
('Mystery Spin Deluxe Megaways', 'Blueprint'),
('Super Lucky Charms', 'Blueprint'),
('Grizzly Gold', 'Blueprint'),
('Super Lucky Frog', 'Blueprint'),
('Kong''s Temple', 'Blueprint'),
('Gong-Hei Gong-Hei', 'Blueprint'),
('Pirates Frenzy', 'Blueprint'),
('Imperial Dragon', 'Blueprint'),
('Ghost Slider', 'Blueprint'),
('Gold Frenzy', 'Blueprint'),
('Wild Spirit', 'Blueprint'),
('Super Jewel Repeater', 'Blueprint'),
('Scribes of Thebes', 'Blueprint'),
('Super Wild Diamonds', 'Blueprint'),
('Dragon''s Flame', 'Blueprint'),
('Woop Woop', 'Blueprint'),
('Red Hot Repeater', 'Blueprint'),
('Super Fortune Dragon', 'Blueprint'),
('Hope Diamond', 'Blueprint'),
('Return Of The Kong', 'Blueprint'),
('Safari Gold', 'Blueprint'),
('Prime Zone', 'Quickspin'),
('Fairy Gate', 'Quickspin'),
('Gold Lab', 'Quickspin'),
('Firestorm', 'Quickspin'),
('The Epic Journey', 'Quickspin'),
('Titan Thunder', 'Quickspin'),
('Sinbad', 'Quickspin'),
('Jewel Blast', 'Quickspin'),
('Sugar Trail', 'Quickspin'),
('Royal Frog 120', 'Quickspin'),
('Durian Dynamite', 'Quickspin'),
('Eastern Emeralds', 'Quickspin'),
('Hammer Of Vulcan', 'Quickspin'),
('Tiger''s Glory', 'Quickspin'),
('Northern Sky', 'Quickspin'),
('Sakura Fortune', 'Quickspin'),
('Skulls UP!', 'Quickspin'),
('Goldilocks', 'Quickspin'),
('Wild Cauldron', 'Quickspin'),
('Sticky Bandits: Wild Return', 'Quickspin'),
('Big Bad Wolf', 'Quickspin'),
('Nero''s Fortune', 'Quickspin'),
('Dragon Chase', 'Quickspin'),
('Hall Of The Mountain King', 'Quickspin'),
('Diamond Duke', 'Quickspin'),
('Sticky Bandits', 'Quickspin'),
('Phoenix Sun', 'Quickspin'),
('Golden Glyph', 'Quickspin'),
('Big Bot Crew', 'Quickspin'),
('Ghost Glyph', 'Quickspin'),
('Hidden Valley 120', 'Quickspin'),
('Vampire Senpai', 'Quickspin'),
('Pirate''s Charm', 'Quickspin'),
('Leprechaun Hills', 'Quickspin'),
('Dwarfs Gone Wild', 'Quickspin'),
('Wild Tome Of The Woods', 'Quickspin'),
('Volcano Riches', 'Quickspin'),
('Illuminous', 'Quickspin'),
('Wins Of Fortune', 'Quickspin'),
('Joker Strike', 'Quickspin'),
('Hot Sync', 'Quickspin'),
('Ivan And The Immortal King', 'Quickspin'),
('Spinions', 'Quickspin'),
('Polar Paws', 'Quickspin'),
('Genies Touch', 'Quickspin'),
('The Wild Chase', 'Quickspin'),
('King Colossus', 'Quickspin'),
('Titan Thunder: Wrath Of Hades', 'Quickspin'),
('Mighty Arthur', 'Quickspin'),
('Panther''s Reign', 'Quickspin'),
('Second Strike', 'Quickspin'),
('Dragon Shrine', 'Quickspin'),
('Wild Chase: Tokyo Go', 'Quickspin'),
('Artemis VS Medusa', 'Quickspin'),
('Ticket To The Stars', 'Quickspin'),
('Divine Dreams', 'Quickspin'),
('Treasure Island', 'Quickspin'),
('Crystal Prince', 'Quickspin'),
('Rapunzel''s Tower', 'Quickspin'),
('Big Bad Wolf Christmas SPecial', 'Quickspin'),
('Arcane Gems', 'Quickspin'),
('Crystal Queen', 'Quickspin'),
('Three Musketeers', 'Quickspin'),
('Sevens High', 'Quickspin'),
('Pied Piper', 'Quickspin'),
('Razortooth', 'Quickspin'),
('Tales Of Dr. Dolittle', 'Quickspin'),
('The Grand', 'Quickspin'),
('Mayana', 'Quickspin'),
('Ark of Mystery', 'Quickspin'),
('Book of Duat', 'Quickspin'),
('Cabin Crashers', 'Quickspin'),
('Spina Colada', 'Yggdrasil'),
('Brazil Bomba', 'Yggdrasil'),
('Football Glory', 'Yggdrasil'),
('Super Heroes', 'Yggdrasil'),
('Orient Express', 'Yggdrasil'),
('Niagara Falls', 'Yggdrasil'),
('Boubles', 'Yggdrasil'),
('Fruitoids', 'Yggdrasil'),
('Chibeasties', 'Yggdrasil'),
('Reef Run', 'Yggdrasil'),
('Moley Moolah', 'Yggdrasil'),
('Cherry Pop', 'Yggdrasil'),
('Temple Stacks: Splitz', 'Yggdrasil'),
('Golden Fishtank', 'Yggdrasil'),
('Nikola Tesla''s Incredible Machine', 'Yggdrasil'),
('Multifly', 'Yggdrasil'),
('Valley Of The Gods 2', 'Yggdrasil'),
('9k Yeti', 'Yggdrasil'),
('Cazino Zeppelin', 'Yggdrasil'),
('Bounty Pop', 'Yggdrasil'),
('Vikings Go Bazerk', 'Yggdrasil'),
('Sahara Nights', 'Yggdrasil'),
('Wild Pops', 'Yggdrasil'),
('Jungle Books', 'Yggdrasil'),
('Hades', 'Yggdrasil'),
('Wolf Hunters', 'Yggdrasil'),
('The One Armed Bandit', 'Yggdrasil'),
('Vikings Go Wild', 'Yggdrasil'),
('Valley Of The Gods', 'Yggdrasil'),
('Wicked Circus', 'Yggdrasil'),
('Hanzo''s Dojo', 'Yggdrasil'),
('PopRocks', 'Yggdrasil'),
('Aldo''s Journey', 'Yggdrasil'),
('Vault Of Fortune', 'Yggdrasil'),
('Lucky Neko', 'Yggdrasil'),
('Easter Island', 'Yggdrasil'),
('Wilhelm Tell', 'Yggdrasil'),
('Tock The Cash Bar', 'Yggdrasil'),
('Trolls Bridge', 'Yggdrasil'),
('Alchymedes', 'Yggdrasil'),
('Legend Of The Golden Monkey', 'Yggdrasil'),
('Ice And Fire', 'Yggdrasil'),
('Champions Of Rome', 'Yggdrasil'),
('Snycronite - Splitz', 'Yggdrasil'),
('Hyper Burst', 'Yggdrasil'),
('2 Gods Zeus Versus Thor', 'Yggdrasil'),
('Pumpkin Smash', 'Yggdrasil'),
('Cazino Cosmos', 'Yggdrasil'),
('Arthurs Fortune', 'Yggdrasil'),
('Age Of Asgard', 'Yggdrasil'),
('Winterberries', 'Yggdrasil'),
('Double Dragons', 'Yggdrasil'),
('Time Travel Tigers', 'Yggdrasil'),
('Christmas Tree', 'Yggdrasil'),
('Dark Vortex', 'Yggdrasil'),
('Big Blox', 'Yggdrasil'),
('Yokozuna', 'Yggdrasil'),
('Victoria Wild', 'Yggdrasil'),
('Beauty And The Beast', 'Yggdrasil'),
('Lightning Joker', 'Yggdrasil'),
('Medusa: Fortune And Glory', 'Yggdrasil'),
('Gem Rocks', 'Yggdrasil'),
('Chibeasties 2', 'Yggdrasil'),
('Avatars Gateway Guardians', 'Yggdrasil'),
('Legend Of The White Snake Lady', 'Yggdrasil'),
('All Star Knockout', 'Yggdrasil'),
('Lucha Maniacs', 'Yggdrasil'),
('Vikings Go To Hell', 'Yggdrasil'),
('Blood Moon Wilds', 'Yggdrasil'),
('Incinerator', 'Yggdrasil'),
('Rainbow Ryan', 'Yggdrasil'),
('Dwarf Mine', 'Yggdrasil'),
('Nirvana', 'Yggdrasil'),
('Pirates 2: Mutiny', 'Yggdrasil'),
('Seasons', 'Yggdrasil'),
('Tut''s Twister', 'Yggdrasil'),
('Elemental Princess', 'Yggdrasil'),
('Power Plant', 'Yggdrasil'),
('Pirates: Smugglers Paradise', 'Yggdrasil'),
('Lilith''s Inferno', 'Yggdrasil'),
('Penguin City', 'Yggdrasil'),
('Wild Robo Factory', 'Yggdrasil'),
('Reptoids', 'Yggdrasil'),
('The Dark Joker Rizes', 'Yggdrasil'),
('Jokerizer', 'Yggdrasil'),
('Sunny Shores', 'Yggdrasil'),
('Baron Samedi', 'Yggdrasil'),
('Bicicleta', 'Yggdrasil'),
('The Royal Family', 'Yggdrasil'),
('Atlantis Megaways', 'Yggdrasil'),
('Carol Of The Elves', 'Yggdrasil'),
('Lady Merlin', 'Yggdrasil'),
('Donuts', 'Big Time Gaming'),
('Extra Chili', 'Big Time Gaming'),
('Danger High Voltage', 'Big Time Gaming'),
('White Rabbit', 'Big Time Gaming'),
('Pirate Pays', 'Big Time Gaming'),
('Bonanza', 'Big Time Gaming'),
('Millionaire', 'Big Time Gaming'),
('Cyberslot MegaClusters', 'Big Time Gaming'),
('Magic Piggy', 'Hacksaw Gaming'),
('Wanted Dead or A Wild', 'Hacksaw Gaming'),
('Stack ''em', 'Hacksaw Gaming'),
('Tasty Treats', 'Hacksaw Gaming'),
('Cubes 2', 'Hacksaw Gaming'),
('Rocket Reels', 'Hacksaw Gaming'),
('Chaos Crew', 'Hacksaw Gaming'),
('Hop ''N'' Pop', 'Hacksaw Gaming'),
('King Carrot', 'Hacksaw Gaming'),
('The Respinners', 'Hacksaw Gaming'),
('The Bowery Boys', 'Hacksaw Gaming'),
('Gladiator Legends', 'Hacksaw Gaming'),
('Toshi Video Club', 'Hacksaw Gaming'),
('Itero', 'Hacksaw Gaming'),
('Time Spinners', 'Hacksaw Gaming'),
('Undead Fortune', 'Hacksaw Gaming'),
('Hand Of Anubis', 'Hacksaw Gaming'),
('Fruit Duel', 'Hacksaw Gaming'),
('Outlaws Inc.', 'Hacksaw Gaming'),
('Dork Unit', 'Hacksaw Gaming'),
('RIP City', 'Hacksaw Gaming'),
('Rotten', 'Hacksaw Gaming'),
('Book of Time', 'Hacksaw Gaming'),
('Bloodthirst', 'Hacksaw Gaming'),
('Alpha Eagle', 'Hacksaw Gaming'),
('Frank''s Farm', 'Hacksaw Gaming'),
('Warrior Ways', 'Hacksaw Gaming'),
('Pug Life', 'Hacksaw Gaming'),
('Gronk''s Gems', 'Hacksaw Gaming'),
('Keep''em Cool', 'Hacksaw Gaming'),
('Stormforged', 'Hacksaw Gaming'),
('Cursed Seas', 'Hacksaw Gaming'),
('Mighty Masks', 'Hacksaw Gaming'),
('Temple of Torment', 'Hacksaw Gaming'),
('Beast Below', 'Hacksaw Gaming'),
('Mayan Stackways', 'Hacksaw Gaming'),
('Drop Em', 'Hacksaw Gaming'),
('Le Bandit', 'Hacksaw Gaming'),
('Densho', 'Hacksaw Gaming'),
('Benny The Beer', 'Hacksaw Gaming'),
('Dark Summonings', 'Hacksaw Gaming'),
('Xmas Drop', 'Hacksaw Gaming'),
('Jingle Balls', 'Hacksaw Gaming'),
('Fireborn', 'Hacksaw Gaming'),
('Immortal Desire', 'Hacksaw Gaming'),
('Ronin Megaways', 'Hacksaw Gaming'),
('Blademaster', 'Hacksaw Gaming'),
('2 Wild 2 Die', 'Hacksaw Gaming'),
('Fear the Dark', 'Hacksaw Gaming'),
('Mafia Clash', 'Hacksaw Gaming'),
('Chaos Crew 2', 'Hacksaw Gaming'),
('Eye of the Panda', 'Hacksaw Gaming'),
('Beam Boys', 'Hacksaw Gaming'),
('Fist of Destruction', 'Hacksaw Gaming'),
('The Cursed King', 'Hacksaw Gaming'),
('Slayers Inc', 'Hacksaw Gaming'),
('Keep Em', 'Hacksaw Gaming'),
('ZE Zues', 'Hacksaw Gaming'),
('Cursed crypt', 'hacksaw Gaming'),
('Le Pharaoh', 'Hacksaw Gaming'),
('Duel at Dawn', 'Hacksaw Gaming'),
('Pirate Bonanza', 'Hacksaw Gaming'),
('Six Six Six', 'Hacksaw Gaming'),
('Cloud Princess', 'Hacksaw Gaming'),
('Rusty & Curly', 'Hacksaw Gaming'),
('Monkey Pop', 'AvatarUX'),
('Hippo Pop', 'AvatarUX'),
('HipHop Pop', 'AvatarUX'),
('Raging Pop', 'AvatarUX'),
('Shifting Seas', 'Thunderpick'),
('Piggy Bjorn Muspelheim''s Treasure', 'Gameart'),
('9 Happy Pharaohs', 'Playson'),
('Bufallo Power Christmas', 'Playson'),
('Live Games', 'Evolution Gaming'),
('Blackjack', 'Evolution Gaming'),
('Treasure Craft', 'Belatra'),
('Shogun''s Fortune', 'Belatra'),
('Chicago Bang Bang', 'Belatra'),
('Mighty Gorilla', 'Booming'),
('Bonus Battles', 'Rollbit'),
('Battles', 'Daddyskins'),
('Euphoria', 'iSoftBet'),
('BONUSHUNT', 'DUAL SLOTS'),
('Double Slots', 'Stake'),
('Take the Kingdom', 'Betsoft'),
('Monster pop', 'Betsoft'),
('Books and Temples', 'Gamomat'),
('Sticky Diamonds', 'Gamomat'),
('Wager Beater', 'SnuggieWoggie Lugono'),
('Twerk', 'Endorphina'),
('Reef Pop', 'Atari'),
('Grand Melee', 'Thunderpick'),
('Merry Scary Christmas', 'Mascot'),
('Christmas Reach Bonus Buy', 'Evoplay'),
('Barbarossa', 'Peter & Sons')
ON CONFLICT (game_name, provider) DO NOTHING;
