-- Add text styling columns to obs_info table
ALTER TABLE obs_info
ADD COLUMN IF NOT EXISTS bold BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS italic BOOLEAN DEFAULT FALSE,
ADD COLUMN IF NOT EXISTS underline BOOLEAN DEFAULT FALSE;
